name: Build Binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    name: Linux Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake build-essential
    - name: Configure
      run: |
        mkdir -p build
        cd build
        cmake ..

    - name: Build Binary
      run: |
        cd build
        make

    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        name: wav_stenography_linux
        path: build/
  build-windows:
    name: Windows Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake mingw-w64

      - name: Configure
        run: |
          mkdir -p build-windows
          cd build-windows
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../toolchain-mingw64.cmake

      - name: Build Binary
        run: |
          cd build-windows
          make

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: wav_stenography_windows
          path: build-windows/
  build-macos:
    name: MacOS Build
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install cmake

      - name: Configure
        run: cmake -S . -B build

      - name: Build Binary
        run: cmake --build build --config Release

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: wav_stenography_mac
          path: build/wav_stenography
